### ISSUE TITLE
Ambiguous class resolution

### ISSUE THREAD

**Issue by modir** [heimrichhannot/contao-calendar_plus#3]
The following warning appears when installing this package with composer:

`Warning: Ambiguous class resolution, "Contao\Versions" was found in both "/website/vendor/heimrichhannot/contao-versions/src/Resources/contao/classes/Versions.php" and "/website/vendor/contao/core-bundle/src/Resources/contao/classes/Versions.php", the first will be used.`

Could it be that your package is not needed anymore as it is now part of the core?

**Comment by koertho** [comment]
Hi, no, our versions module is an extension to the contao version class. But to be honest, it is really old and I think we don't use it anymore in our new bundles. But it won't be fixed for this module, since we let it run out.
