### ISSUE TITLE
decentList etc. in event_list.html5 & event_full.html5

### ISSUE THREAD

**Issue by jankout** [heimrichhannot/contao-calendar_plus#5]
Hello, 

I would like to keep using your extension with the current version of Contao (at the moment 4.9.x). Especially the function for moderators, organisers and docents is very helpful and useful for me. 

I would like to output the data for the mentioned fields from given event in **_event_list.html5_** & **_event_full.html5_** without using your template eventmodal_full.html5. Is it posible? If yes, could you post the code here, please?

If I can support you somehow to keep developing and improving the extension, please let me know. Thank you.

**Comment by koertho** [comment]
@jankout I don't know which data you need, but why don't you just take the template variables and output them in your template?

**Comment by jankout** [comment]
I would like to output docents - I added there more fields (_docentInfo, docentPicture, imageSize, target_) with my extension. But if I take your `foreach` command for `docentList` from your `eventmodal_full.html5` it doesn’t  work. 

This is the part from your template I would like to use in **_layout_list.html5_** and _**layout_full.html5**_

```
<?php if (is_array($this->docentList) && !empty($this->docentList)): ?>
                <div class="docents">
                    <span class="text-muted"><?php echo $GLOBALS['TL_LANG']['event']['docentLabel']; ?></span>
                    <?php foreach ($this->docentList as $i => $docent): ?>
                        <span class="docent"><?php echo $docent->title; ?> <?php if ($i + 1 < count($this->docentList)): ?> &middot; <?php endif; ?></span>
                    <?php endforeach; ?>
                </div>
<?php endif; ?>
```

**Comment by jankout** [comment]
[There is also a post from me in the Contao forum, if you prefer to communicate there. ](https://community.contao.org/de/showthread.php?77524-calendar_plus-Ausgabe-von-Kindtabelle-in-Template#post522316)

**Comment by jankout** [comment]
Any idea? I would appreciate it very much. :-)

**Comment by koertho** [comment]
@jankout Do you use the correct frontend module (eventreader_plus, (Erweiterter Eventleser))? 

BTW: we don't use the contao forum ;) but I'm more or less active in the contao slack channel. But for bundle support please use the github issues.

**Comment by jankout** [comment]
Ok. If I use your _**Erweiterte Eventliste**_ and my **_event_list.html5_** with this command 

  ```
 <?php if ($this->docents): ?>
                <div class="docents">
                    <?php foreach ($this->docentList as $i => $docent): ?>
                        <span class="docent">
                    <?php echo $docent->title; ?><?php echo $docent->docentInfo; ?> <?php if ($i + 1 < count($this->docentList)): ?> &middot; <?php endif; ?></span>
                    <?php endforeach; ?>
                </div>
    <?php endif; ?>
```
I can see the result for the title. 

But as I already wrote above I added some custom fields (_docentInfo, docentPicture, imageSize, target_) with my own extensions and I need to output them too. 

If I correctly understand the structure and logic of your extension I guess I need to extend your _**CalendarDocentsModel.php**_ in my extension, do I? If yes, could you give me some advice what I should do to output my additional fields?

**Comment by koertho** [comment]
Ok, so you try to add this code to a custom frontend module, I'am right? This wasn't clear from what you wrote. I this case, you could extend it from our module, if possible. The docent variables are generated in the EventsPlus class. Maybe you can use this somehow.

**Comment by jankout** [comment]
Thomas, I appreciate your help very much. 

My question is: Can I do it when I extend your **_CalendarDocentsModel.php_** like this in my extension for each additional field I have? 

```
<?php
namespace HeimrichHannot\CalendarPlus;


class CalendarDocentsModelPlus extends \HeimrichHannot\CalendarPlus\CalendarDocentsModel
{
    protected static $strTable = 'tl_calendar_docents';

    /**
     * Find all item by pids array
     *
     * @param array $arrOptions An optional options array
     *
     * @return \Model\Collection|null A collection of models or null if no items found
     */
    public static function findByPids(array $arrPids = [], array $arrOptions = [])
    {
        if (!is_array($arrPids) || empty($arrPids))
        {
            return null;
        }

        $t = static::$strTable;

        $arrPids = array_map('intval', $arrPids);

        $arrColumns[] = "($t.pid IN (" . implode(',', $arrPids) . "))";

        return static::findBy($arrColumns, null, $arrOptions);
    }

    /**
     * Find all items by docentInfo
     *
     * @param string $varValue   The title value
     * @param array  $arrOptions An optional options array
     *
     * @return \Model\Collection|null A collection of models or null if the title was not found
     */
    public static function findByInfo($docentInfo, array $arrOptions = [])
    {
        $t = static::$strTable;

        return static::findBy(["LOWER($t.docentInfo) LIKE ?"], [strval(strtolower($docentInfo))], $arrOptions);
    }

    public function generateAlias()
    {
        $varValue = standardize(\StringUtil::restoreBasicEntities($this->docentInfo));

        $objAlias = static::findBy('alias', $varValue);

        // Check whether the alias exists
        if ($objAlias !== null)
        {
            if (!$this->id)
            {
                return $this;
            }

            $varValue .= '-' . $this->id;
        }

        $this->alias = $varValue;

        return $this;
    }
}
```

Or need I additionally to add also an own class and register it?

**Comment by koertho** [comment]
From my opinion you do not need to extend the model class, since contao models have all fields available. You want the additional variables in your template, so you need to add them in your frontend module. So you either need a hook if available or you need to create a custom frontend module or just use out frontend module.

**Comment by jankout** [comment]
Thank you for your respond. It sounds like there are more possibilities. Which one is the best one with Contao 4.9.x and for me? What would you recommend me?

**Comment by koertho** [comment]
Sorry, I don't know what kind of extension your are developing and it sounds a little as your are new into contao development? If this is true, please read into the [contao docs](https://docs.contao.org/dev/), especial the chapters about hooks and frontend modules.
My recommendation, when extending another bundle, is to do this with a hook or an event. Custom frontend module, just to extend another bundles functionality should be avoided (we've done this in our old module a lot at it wasn't good). Hooks/Events are easer to use and more update save (but sadly there are often to few if none available). But I'm not not into this or the core bundles calendar code to know if there are (usefull) hook available.

**Comment by jankout** [comment]
Dear Thomas, as I already wrote [above](https://github.com/heimrichhannot/contao-calendar_plus/issues/5#issuecomment-604868282) I just added a few fields (`docentInfo`, `docentPicture`, `imageSize`, `target`) to the docents table `tl_calendar_docents` and I would like to output them in the mentioned templates. Nothing more, nothing less. My extension/module is very simple and based on the Contao 3 logic - I put it into `system/modules`.

If you could add this additional fields it would be amazing, of course. In this case I wouldn't need to develop anything on my own. But I guess you don't want to develop this extension any more as I read it somewhere.

**Comment by koertho** [comment]
So why you not just use our frontend module with a custom template?

**Comment by jankout** [comment]
Well, I'm using it but my question is all the time how I can output my additional fields.

**Comment by koertho** [comment]
For custom fields from other tables the techniques is the same: Hook or Custom Frontend Module. There is a hook (see readme) where you maybe could add your custom fields. Maybe there is also a hook from the contao core.

**Comment by jankout** [comment]
Thank you. I will try it.
