### ISSUE TITLE
Contao 4.10.x scheitert an der Installation

### ISSUE THREAD

**Issue by jankout** [heimrichhannot/contao-calendar_plus#6]
Hallo, 

wenn ich Ihre Erweiterung mit Contao 4.10.x installieren möchte, kommt es zur folgenden Fehlermeldung: 

`Could not parse version constraint >=1.0.14,,<2.0.0-dev: Invalid version string "1.0.14,,<2.0.0-dev"`

`Could not load package heimrichhannot/contao-formhybrid in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint >=1.0.14,,<2.0.0-dev: Invalid version string "1.0.14,,<2.0.0-dev"`

Ich habe es schon bei der anderen Erweiterung gemeldet, allerdings wurde ich auf diese verwiesen. https://github.com/heimrichhannot/contao-formhybrid/issues/6

**Comment by koertho** [comment]
@jankout Welche Version von Calendar_plus wird installiert? Kannst du composer nutzen?

**Comment by jankout** [comment]
Contao Manager bietet mir die letzte Version. Wenn ich das manuell auf ^2.3 ändere, passiert der Fehler auch. Ich nutze die letzte Version von Contao Manager und Contao.

**Comment by koertho** [comment]
"Letzte Version" ist keine definitive Aussage, da sich die Version ändern kann. Ich gehe aber mal von Version 2.3.2 aus.
Ich vermute mal, folgende Abhängigkeit von Formhybrid führt zu dem Fehler: `"heimrichhannot/contao-submissions": ">=1.0.14,<2.0.0-dev"`. Ist leider aus dem gegebenen Fehler-Log nicht einfach ersichtlich. 
Kurioserweise hatten wir in diesem Bezug kein Fehler, nutzen allerdings keinen Contao-Manager, eventuell interpretiert dieser Versionstrings etwas anders. Könntest du es mit composer direkt testen?

**Comment by jankout** [comment]
Das kann ich leider nicht. 

In Contao Manager stand _Letzte Version_, also gehe ich davon aus, dass das die letzte Version ist. ;-)

**Comment by koertho** [comment]
Hi, ist lange her. Ich habe gerade bei Formhybrid den Versions-String angepasst, da es mir gerade vor die Füße lief. Kannst gern mal Feedback geben, sonst schließe ich hier.

**Comment by jankout** [comment]
Hi, jetzt geht es ganz gut. Vielen Dank für die Anpassung.
